package main.java.client;
import com.intellij.uiDesigner.core.GridLayoutManager;
import main.java.client.listeners.ClientAppListener;
import main.java.client.listeners.ClientLoginListener;
import main.java.client.listeners.ClientMenuListener;
import main.java.client.listeners.ClientOrderListener;
import main.java.client.ui.ClientFrameApp;
import main.java.client.ui.ClientFrameLogin;
import main.java.client.ui.ClientFrameMenu;
import main.java.client.ui.ClientFrameOrder;
import main.java.model.*;

import javax.swing.*;
import java.awt.*;

public class ClientFrameMain extends JFrame {

    /*
        scene:
            0 - Login
            1 - Menu
            2- Main
     */

    public static int LOGIN_SCENE = 0;
    public static int MENU_SCENE = 1;
    public static int MAIN_SCENE = 2;
    public static int ORDER_SCENE = 3;

    ClientModel model;

    //Frame Login
    ClientLoginListener cll = new ClientLoginListener(this);
    ClientFrameLogin clientFrameLogin;

    //Frame app
    ClientAppListener cal = new ClientAppListener(this);
    ClientFrameApp clientFrameApp;

    //Frame menu
    ClientMenuListener cml = new ClientMenuListener(this);
    ClientFrameMenu clientFrameMenu;

    //Frame order
    ClientOrderListener col = new ClientOrderListener(this);
    ClientFrameOrder clientFrameOrder;


    public ClientFrameMain() {

        setScene(LOGIN_SCENE); // Login scene by default
        model = new ClientModel();

        this.setTitle("Client Local Delivery");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(new Dimension(clientFrameLogin.getAppWidth(), clientFrameLogin.getAppHeight()));
        this.setLocationRelativeTo(null); // Center app
        this.setVisible(true);
    }

    public void setScene(int scene) {
        if (scene == LOGIN_SCENE) {
            clientFrameLogin = new ClientFrameLogin(cll);
            this.setSize(new Dimension(clientFrameLogin.getAppWidth(), clientFrameLogin.getAppHeight()));
            this.setLocationRelativeTo(null); // Center app
            this.setContentPane(clientFrameLogin.getContentPane());
        } else if (scene == MENU_SCENE) {
            clientFrameMenu = new ClientFrameMenu(cml);
            this.setSize(new Dimension(clientFrameMenu.getAppWidth(), clientFrameMenu.getAppHeight()));
            this.setLocationRelativeTo(null); // Center app
            this.setContentPane(clientFrameMenu.getContentPane());
        } else if (scene == MAIN_SCENE) {
            clientFrameApp = new ClientFrameApp(this.model, cal);
            this.setSize(new Dimension(clientFrameApp.getAppWidth(), clientFrameApp.getAppHeight()));
            this.setLocationRelativeTo(null); // Center app
            this.setContentPane(clientFrameApp.getContentPane());
        } else if (scene == ORDER_SCENE) {
            clientFrameOrder = new ClientFrameOrder(this.model, col);
            this.setSize(new Dimension(clientFrameOrder.getAppWidth(), clientFrameOrder.getAppHeight()));
            this.setLocationRelativeTo(null); // Center app
            this.setContentPane(clientFrameOrder.getContentPane());
        }
        this.setVisible(true);
//        this.repaint(); // Repaint to refresh screen
    }


    public ClientFrameLogin getClientFrameLogin() {
        return clientFrameLogin;
    }

    public ClientFrameApp getClientFrameApp() {
        return clientFrameApp;
    }

    public ClientFrameMenu getClientFrameMenu() {
        return clientFrameMenu;
    }

    public ClientFrameOrder getClientFrameOrder() {
        return clientFrameOrder;
    }

    public ClientModel getModel() {
        return model;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
