package main.java.server;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import main.java.server.listeners.MainServerListener;

import javax.swing.*;
import java.awt.*;

public class ServerFrameMain extends JFrame {

    public JPanel mainPanel;
    MainServerListener msl;
    ServerFrameApp sfa;

    public static int MAIN_SCENE = 0;

    public ServerFrameMain() {
        setScene(MAIN_SCENE);

        this.setTitle("Local Delivery - Server");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(new Dimension(sfa.getAppWidth(), sfa.getAppHeight()));
        this.setLocationRelativeTo(null); // Center app
        this.setVisible(true);
    }

    public void setScene(int scene) {

        if (scene == MAIN_SCENE) {
            msl = new MainServerListener(this);
            sfa = new ServerFrameApp(msl);
            this.setSize(new Dimension(sfa.getAppWidth(), sfa.getAppHeight()));
            this.setLocationRelativeTo(null); // Center app
            this.setContentPane(sfa.getContentPane());
        }

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
