package main.java.server;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import main.java.server.listeners.MainServerListener;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class ServerFrameApp extends JFrame {
    public JPanel mainPanel;
    public JList listOrder;
    public JPanel exitPanel;
    public JButton exitBtn;
    public JPanel rightPanel;
    public JComboBox userCombo;
    public JPanel leftPanel;
    public JButton viewMapButton;
    public JPanel detailsPanel;
    public JPanel viewMapPanel;

    private int appWidth = 800;
    private int appHeight = 600;

    MainServerListener msl;

    public ServerFrameApp(MainServerListener msl) {
        this.msl = msl;
        $$$setupUI$$$();
        setContentPane(mainPanel);
        assignListeners();
    }

    public int getAppWidth() {
        return appWidth;
    }

    public void setAppWidth(int appWidth) {
        this.appWidth = appWidth;
    }

    public int getAppHeight() {
        return appHeight;
    }

    public void setAppHeight(int appHeight) {
        this.appHeight = appHeight;
    }

    private void createUIComponents() {
        rightPanel = new JPanel();
        exitBtn = new JButton("Exit");
//        mapPanel.add(new JFrame());
    }

    private void assignListeners()
    {
        exitBtn.addActionListener(this.msl);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        exitPanel = new JPanel();
        exitPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(exitPanel, BorderLayout.SOUTH);
        exitBtn.setText("Exit");
        exitPanel.add(exitBtn, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rightPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(rightPanel, BorderLayout.CENTER);
        viewMapPanel = new JPanel();
        viewMapPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        rightPanel.add(viewMapPanel, BorderLayout.SOUTH);
        viewMapButton = new JButton();
        viewMapButton.setText("View Map");
        viewMapPanel.add(viewMapButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        detailsPanel = new JPanel();
        detailsPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        rightPanel.add(detailsPanel, BorderLayout.CENTER);
        leftPanel = new JPanel();
        leftPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(leftPanel, BorderLayout.WEST);
        leftPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        userCombo = new JComboBox();
        leftPanel.add(userCombo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, -1), null, 0, false));
        listOrder = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        listOrder.setModel(defaultListModel1);
        listOrder.setPreferredSize(new Dimension(200, 0));
        leftPanel.add(listOrder, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
