package main.java.client.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import main.java.client.listeners.ClientLoginListener;
import main.java.component.JLabelC;
import main.java.component.customJPanel.JPanelBackground;

import javax.swing.*;
import java.awt.*;
import java.net.URL;

public class ClientFrameLogin extends JFrame {

    private int appWidth = 500;
    private int appHeight = 300;

    private JPanel mainPanel;
    private JButton loginBtn;
    private JLabel titleLabel;
    private JLabel usrLabel;
    private JLabel passLabel;
    private JPanel loginPanel;
    private JPanel titlePanel;
    private JPanel userWrapper;
    private JTextField username;
    private JPasswordField password;
    private JPanel userLineWrapper;

    ClientLoginListener cll;

    /**
     * Constructor
     */
    public ClientFrameLogin(ClientLoginListener cll) {
        this.cll = cll;
        $$$setupUI$$$();
        this.setContentPane(mainPanel);
        assignListeners();
    }

    /**
     * Custom UI components when creating form
     */
    private void createUIComponents() {
//        String path = System.getProperty("user.dir") + "/src/main/resources/images/background.jpg";
        URL url = this.getClass().getResource("../../../resources/images/background.jpg");
        System.out.println(url);
        mainPanel = new JPanelBackground(url);

        titleLabel = new JLabelC("LOCAL DELIVERY");
        titleLabel.setSize(new Dimension(200, 300));

    }

    private void assignListeners() {
        loginBtn.addActionListener(cll);
    }

    public int getAppWidth() {
        return appWidth;
    }

    public void setAppWidth(int appWidth) {
        this.appWidth = appWidth;
    }

    public int getAppHeight() {
        return appHeight;
    }

    public void setAppHeight(int appHeight) {
        this.appHeight = appHeight;
    }

    public String getUsernameValue() {
        return username.getText();
    }

    public char[] getPasswordValue() {
        return password.getPassword();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setOpaque(true);
        userWrapper = new JPanel();
        userWrapper.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        userWrapper.setOpaque(false);
        mainPanel.add(userWrapper, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        userLineWrapper = new JPanel();
        userLineWrapper.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        userLineWrapper.setOpaque(false);
        userWrapper.add(userLineWrapper, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        usrLabel = new JLabel();
        usrLabel.setText("Username:");
        userLineWrapper.add(usrLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        username = new JTextField();
        username.setOpaque(false);
        userLineWrapper.add(username, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passLabel = new JLabel();
        passLabel.setText("Password:");
        userLineWrapper.add(passLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        password = new JPasswordField();
        password.setOpaque(false);
        userLineWrapper.add(password, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        titlePanel = new JPanel();
        titlePanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        titlePanel.setOpaque(false);
        mainPanel.add(titlePanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        titleLabel.setEnabled(true);
        titleLabel.setVerifyInputWhenFocusTarget(true);
        titlePanel.add(titleLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(37, 74), null, 0, false));
        loginPanel = new JPanel();
        loginPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        loginPanel.setOpaque(false);
        mainPanel.add(loginPanel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        loginBtn = new JButton();
        loginBtn.setOpaque(false);
        loginBtn.setText("Login");
        loginPanel.add(loginBtn, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(160, -1), new Dimension(160, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
